### ISSUE TITLE
New Features: Overloads, Flasks, Quick Prayers, Multiple Alert Names

### ISSUE THREAD

**Issue by Magnificoman** [PBLord/Parabot-Script-errors#6]
_**Four things that would really improve the quality of the script**_

**Add Overloads**
Is incredibly beneficial for high level PvM and facilitates every combat style. Accessible to every player.

**Flask compatibility**
For both restores and overloads, make the bot recognize either regular potions or flasks in the inventory. Alternatively, the user could select an option for it.

**Quick Prayers** 
People mostly range for high level PvM, so turmoil is a worthless prayer. Giving us the option to set quick prayers would allow us to use the offensive range or mage prayers.

**Multiple Name Notification**s 
This would allow you to add several variations of your name to the notification list. If the account has a longer name, people are likely to not type the entire thing.

**Comment by George-Farrell** [comment]
Accepted
